### ISSUE TITLE
Cria/Rose-2: my results are way worse than the paper's

### ISSUE THREAD

**Issue by BenjaminBo** [iMED-Lab/OCTA-Net-OCTA-Vessel-Segmentation-Network#17]
I ran your code's first- and second stage and I am confused why I get such worse results than are described in the paper.

I ran the first stage with the `resnest50-528c19ca.pth` and I linked for my second stage with the `[...]best-fusion.pth`, `[...]best-thick.pth` and the `[...]best-thin.pth` models, generated by the first stage, to the `suffix`-variables. 

**Quantitative results for the fusion step:**

![octa_acc](https://user-images.githubusercontent.com/26384702/184878534-376f3eb6-9c60-419b-b347-a3eb5a105dba.png)

![octa_auc](https://user-images.githubusercontent.com/26384702/184878557-28192e71-3643-4cb9-bbd9-4bd0de09b0e3.png)

![octa_dice](https://user-images.githubusercontent.com/26384702/184878563-b618bd15-a761-408a-b09c-2f1788ca0671.png)

![octa_iou](https://user-images.githubusercontent.com/26384702/184878606-98f124a8-0221-4a37-ae8b-8f9a227b32f9.png)

AUC and ACC are fairly close, but DICE, the metric I find the most relevant, caps at around 0.41, which is way worse than what you wrote in your paper (0.7077)

**Qualitative results for the fusion step:**

![11_OD_SVP](https://user-images.githubusercontent.com/26384702/184880075-ca7b9380-114b-41c4-8b7d-e6535c402b60.png)

![25_OD_SVP](https://user-images.githubusercontent.com/26384702/184880104-9ef46d2d-2b91-48a9-85d6-3ba173fedd38.png)

![25_OS_SVP](https://user-images.githubusercontent.com/26384702/184880116-4055cec8-b109-4e41-ae50-92d08cef3fff.png)

We were interested in this paper because of the prospect of filtering out artifacts on OCTA images. These images above are probably the most extreme examples on the test set, but I don't see the models that I have trained, as acceptable enough to use.

**Conclusion:**
I have no trouble believing that I messed up somewhere, which would explain why I get such bad results. I just don't know where.

I have not used the `front_model-189-0.9019971996250081.pth` for the second stage, that you linked [here](https://pan.baidu.com/s/1S852PenfG50JRWK33Zz5kg). The download doesn't give me the file that I want but an .exe called `BaiduNetdisk_7.19.0.18`. I don't know what to do with that and I have no administrative rights here, so I can't launch the installation that it is trying to launch.
Could you maybe upload the  `front_model-189-0.9019971996250081.pth` - like you did for `resnest50-528c19ca.pth` (https://github.com/iMED-Lab/OCTA-Net-OCTA-Vessel-Segmentation-Network/issues/2) - on a drive? I would like to know if I can reproduce the results of your paper with that model.

Also concerning the `front_model-189-0.9019971996250081.pth`: Is this a fusion-, thin- or thick-model?

**Comment by BenjaminBo** [comment]
I just read [here](https://github.com/iMED-Lab/OCTA-Net-OCTA-Vessel-Segmentation-Network/issues/12#issuecomment-877734288) that you said, that both stages had to be run with the fixes given in the thread. I ran my first stage without those fixes and then my second stage with them.

I am now rerunning both stages with the fixes and will get back at you, when I have the results.

**Comment by BenjaminBo** [comment]
Okay so what I have reported in my first comment still holds true. I was not able to reproduce your results. 

Accordingly, it would be great if you could upload the `front_model-189-0.9019971996250081.pth` on a google drive - like you did for the `resnest50-528c19ca.pth` -  and explain what variable to set to its path.

**Comment by aylin-msvn** [comment]
@BenjaminBo Would you please rephrase how you run this code, I'm facing with this error when it's trying to load resnest50-528c19ca.pth from url_format variable indicated in resnest.py

_url_format = 'https://hangzh.s3.amazonaws.com/encoding/models/{}-{}.pth'

request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by BenjaminBo** [comment]
I downloaded the ``resnest50-528c19ca.pth`` as described in #2. It's the second link I believe. I then used the downloaded .pth in the repos.

I'm not sure what this error is, that you're showing me, but you seem to download it at runtime? Maybe that's the problem.

**Comment by aylin-msvn** [comment]
@BenjaminBo Thank you so much for the contribution 🙏🏻

**Comment by BenjaminBo** [comment]
No problem. If you get to reproduce the results from the paper or get better results than I did, tell me how you did it :)

**Comment by aylin-msvn** [comment]
@BenjaminBo Sure, I will keep you posted about my running, Could I have your email address to be able get in touch rather than here? Mine is: aylin.msvn@gmail.com

**Comment by aylin-msvn** [comment]
@BenjaminBo  after downloading resnest50-528c19ca.pth, I ran program, but I faced with this error:

  File "/Users/miniforge3/envs/torch-gpu/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Start training...
Epoch 1 / 300
----------
Traceback (most recent call last):
  File "<string>", line 1, in <module>

There is something wrong with dataloader I think. I was wondering did you change some lines in options.py inside your code? 
I just changed data_dir to load the image dataset, what else I need to change? That would be greatly appreciated if you help me with this issue,

**Comment by aylin-msvn** [comment]
@BenjaminBo How was your results on front_main step? I got the results on that step almost like the paper
